name: debianCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-pull/${{ github.event.number }}
  cancel-in-progress: true

jobs:
  debian-check:
    uses: linuxdeepin/.github/.github/workflows/debian-check.yml@master
