name: Call dtk-unittest

on:
  push:
    paths-ignore:
      - ".github/workflows/**"
  pull_request_target:
    paths-ignore:
      - ".github/workflows/**"

jobs:
  check_job:
    uses: linuxdeepin/.github/.github/workflows/dtk-unittest.yml@master
