name: backup to gitlab
on: [push]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  backup-job:
    uses: linuxdeepin/.github/.github/workflows/backup-repo.yml@master
    secrets:
      BRIDGETOKEN: ${{ secrets.BRIDGETOKEN }}
      GITEE_SYNC_TOKEN: ${{ secrets.GITEE_SYNC_TOKEN }}
