name: backup to gitlabwh
on:
  workflow_call:
    secrets:
      BRIDGETOKEN:
        required: true

jobs:
  backup-to-gitlabwh:
    if: false
    name: backup-to-gitlab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "linuxdeepin/jenkins-bridge-client"
          path: jenkins-bridge-client

      - name: Install Client
        run: |
          cd $GITHUB_WORKSPACE/jenkins-bridge-client
          go build .
          sudo install -Dvm755 jenkins-bridge-client -t /usr/bin/

      - name: Trigger sync
        id: generate-runid
        run: |
          echo "RUN_ID=$(jenkins-bridge-client triggerSync --token '${{ secrets.BRIDGETOKEN }}')" >> $GITHUB_OUTPUT

      - name: Print log
        run: |
          jenkins-bridge-client printLog --token "${{ secrets.BRIDGETOKEN }}" --runid "${{ steps.generate-runid.outputs.RUN_ID }}"
