name: Backup all repos to gitlabwh on a schedule
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  backup:
    if: github.repository_owner == 'linuxdeepin'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "linuxdeepin/jenkins-bridge-client"
          path: jenkins-bridge-client
      - name: Install Client
        run: |
          cd $GITHUB_WORKSPACE/jenkins-bridge-client
          go build .
          sudo install -Dvm755 jenkins-bridge-client -t /usr/bin/
      - uses: actions/checkout@v2
      - run: bash ".github/workflows/backup-all-repos-to-gitlabwh.bash" linuxdeepin ${{ secrets.BridgeToken }}
