name: Debian Check
on: 
  workflow_call:
    inputs:
      job_name:
        required: false
        type: string

env:
  repository: ${{ github.repository }}
  access_token: ${{ secrets.GITHUB_TOKEN }}
  job_name: ${{ inputs.job_name }}
  pull_number: ${{ github.event.pull_request.number }}
  ref_type: ${{ github.ref_type }}
  head_ref: ${{ github.head_ref }}
  
jobs:
  Check-Debian-Prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'debian/**'
          files_ignore: |
            debian/patches/*
            debian/manpage.*
            debian/*.manpages
            debian/changelog
            debian/copyright
            debian/compat
            debian/source/format
      - name: List all changed files
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        env:
          DEBIAN_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          if [ ! -z ${DEBIAN_CHANGED_FILES} ]; then
            echo "list all debian files that have changed: $DEBIAN_CHANGED_FILES"
            exit 1
          fi
  Check-Specical-Words:
    runs-on: ubuntu-latest
    steps:
      - name: Check Specical Words
        env:
          FILTER_KEYS: "getcap,setcap,lshw,dmidecode"
        run: |
          wget -O debian-check.py https://raw.githubusercontent.com/linuxdeepin/.github/master/.github/tools/debian-check.py
          wget -O getGithubChangeInfo.py https://raw.githubusercontent.com/linuxdeepin/.github/master/.github/tools/getGithubChangeInfo.py
          python3 debian-check.py --type keys-check --keys $FILTER_KEYS --log keys.json
      - name: Publish reports
        if: always() && hashFiles('keys.json')
        uses: actions/upload-artifact@v4
        with:
          name: specical-keys-check-artifact
          path: keys.json
      - name: Comment PR
        if: always() && hashFiles('comment.txt')
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment.txt
  Check-Env-Set-Words:
      runs-on: ubuntu-latest
      steps:
        - name: Check Env Set Words
          env:
            FILTER_KEYS: "export,unset"
          run: |
            wget -O debian-check.py https://raw.githubusercontent.com/linuxdeepin/.github/master/.github/tools/debian-check.py
            wget -O getGithubChangeInfo.py https://raw.githubusercontent.com/linuxdeepin/.github/master/.github/tools/getGithubChangeInfo.py
            python3 debian-check.py --type keys-check --keys $FILTER_KEYS --log env-keys.json
        - name: Publish reports
          if: always() && hashFiles('env-keys.json')
          uses: actions/upload-artifact@v4
          with:
            name: env-set-words-check-artifact
            path: env-keys.json
        - name: Comment PR
          if: always() && hashFiles('comment.txt')
          uses: thollander/actions-comment-pull-request@v2
          with:
            filePath: comment.txt