name: Debian Check Post
on: 
  workflow_call:
    inputs:
      debian-check-prefix-status:
        required: true
        type: string
      debian-check-prefix-msg:
        required: true
        type: string
      debian-check-version-status:
        required: true
        type: string
      debian-check-version-msg:
        required: true
        type: string
      debian-check-key-status-env:
        required: true
        type: string
      debian-check-key-msg-env:
        required: true
        type: string
      debian-check-key-status:
        required: true
        type: string
      debian-check-key-msg:
        required: true
        type: string

env:
  APP_ID: ${{ secrets.APP_ID }}
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

jobs:
  debian-check-post:
    runs-on: ubuntu-latest
    steps:
      - id: get-comment-file
        run: |
          if [ ${{ inputs.debian-check-prefix-status }} == 'failure' ];then
            echo "${{ inputs.debian-check-prefix-msg }}" >> comment.txt
          fi
          if [ ${{ inputs.debian-check-version-status }} == 'failure' ];then
            echo "${{ inputs.debian-check-version-msg }}" >> comment.txt
          fi
          if [ ${{ inputs.debian-check-key-status-env }} == 'failure' ];then
            echo "${{ inputs.debian-check-key-msg-env }}" >> comment.txt
          fi
          if [ ${{ inputs.debian-check-key-status }} == 'failure' ];then
            echo "${{ inputs.debian-check-key-msg }}" >> comment.txt
          fi
          if [ -e 'comment.txt' ];then
            sed -i '1i [Debian检查]:' comment.txt
          fi
      - name: Comment PR
        if: hashFiles('comment.txt')
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment.txt
      - name: install depends for load scripts
        if: hashFiles('comment.txt')
        run: |
          npm install @octokit/rest@19.0.13
          npm install @octokit/auth-app@6.1.1
      - name: Get token using github-script
        id: get-token
        if: hashFiles('comment.txt')
        uses: actions/github-script@v6
        with:
          script: |
            global["fetch"] = fetch
            const { Octokit } = require("@octokit/rest");
            const { createAppAuth } = require("@octokit/auth-app");
            const appOctokit = new Octokit({
              authStrategy: createAppAuth,
              auth: {
                appId: process.env.APP_ID,
                privateKey: process.env.APP_PRIVATE_KEY,
              }
            });
            const app_installation = await appOctokit.rest.apps.getRepoInstallation({
              owner: context.payload.organization.login,
              repo: context.payload.repository.name
            });
            const { token } = await appOctokit.auth({
              type: "installation",
              installationId: app_installation.data.id
            });
            core.setOutput('app_token', token)
      - name: Run assignment of reviewer team
        id: add-reviewer-team
        continue-on-error: true
        if: hashFiles('comment.txt')
        uses: ryaugusta/pr-add-reviewers-action@v1
        with:
          token: ${{ steps.get-token.outputs.app_token }}
          team_reviewers: Package-admins
      - name: Run assignment of reviewers
        if: ${{ hashFiles('comment.txt') && steps.add-reviewer-team.outcome == 'failure' }}
        uses: ryaugusta/pr-add-reviewers-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: liujianqiang-niu
