name: Debian Check
on: workflow_call

permissions: write-all

jobs:
  call-debian-check-prefix:
    uses: linuxdeepin/.github/.github/workflows/debian-check-prefix.yml@master
  call-debian-check-version:
    uses: linuxdeepin/.github/.github/workflows/debian-check-version.yml@master
  call-debian-check-keys:
    uses: linuxdeepin/.github/.github/workflows/debian-check-keys.yml@master
