name: Debian Check Prefix
on: 
  workflow_call:
    outputs:
      check_msg:
        description: "output comment msg"
        value: ${{ jobs.debian-check-prefix.outputs.check_msg }}
      check_status:
        description: "check status"
        value: ${{ jobs.debian-check-prefix.outputs.check_status }}

jobs:
  debian-check-prefix:
    runs-on: ubuntu-latest
    outputs:
      check_msg: |
        检测到debian目录文件有变更: ${{ steps.get-changed-files.outputs.all_changed_files }}
      check_status: ${{ steps.check-changed-files.outcome }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get changed files
        id: get-changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'debian/**'
          files_ignore: |
            debian/patches/*
            debian/manpage.*
            debian/*.manpages
            debian/changelog
            debian/copyright
            debian/compat
            debian/source/format
      - name: Check changed files
        id: check-changed-files
        if: steps.get-changed-files.outputs.all_changed_files
        run: |
          echo "debian目录变动文件: ${{ steps.get-changed-files.outputs.all_changed_files }}"
          exit 1