name: debianCheck
on: workflow_call


jobs:
  debian-check:
    runs-on: ubuntu-latest
    steps:
      - id: debian-check
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@debian-check
      - if: always() && steps.debian-check.outputs.summary-status == '否'
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@post-check
        with:
          comment-file: summary-comment.txt
          reviewers: liujianqiang-niu
      - if: always()
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@send-data
        with:
          testtype: "debianCheck"
          status: ${{ steps.debian-check.outputs.summary-status }}
          result: ${{ steps.debian-check.outputs.summary-result }}
      - if: always() && steps.debian-check.outputs.summary-status == '否'
        run: exit 1