name: Debian Check
on: workflow_call

jobs:
  Check-Debian-Prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'debian/**'
          files_ignore: |
            debian/patches/*
            debian/manpage.*
            debian/*.manpages
            debian/changelog
            debian/copyright
            debian/compat
            debian/source/format
      - name: List all changed files
        if: steps.changed-files.outputs.all_changed_files
        env:
          DEBIAN_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          if [ ! -z ${DEBIAN_CHANGED_FILES} ]; then
            echo "list all debian files that have changed: $DEBIAN_CHANGED_FILES"
            exit 1
          fi
  Check-Version-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'debian/changelog'
      - name: Check Version
        if: steps.changed-files.outputs.all_changed_files
        run: |
          result=$(echo ${repository} | grep "/" || true)
          project_tmp=${repository}
          if [[ "$result" != "" ]]; then
              project_tmp=$(echo ${repository} | awk -F'/' '{print $2}' || true)
          fi
          version_str=$(dpkg-parsechangelog -l debian/changelog -n 2|grep ${project_tmp}|awk -F'[()]' '{print $2}'|grep -v '^$\|^Task\|^Bug\|^Influence'|tr '\n' ' '|| true)
          version_num=$(echo $version_str|awk '{print NF}' || true)
          echo "version_str is ${version_str}"
          echo "version_num is ${version_num}"
          if [[ "$version_num" == "2" ]]; then
              version0=$(echo $version_str|awk '{print $1}' || true)
              version1=$(echo $version_str|awk '{print $2}' || true)
              check_result=$(dpkg --compare-versions ${version0} gt ${version1} && echo true || echo false)
              if [[ "$check_result" == "false" ]];then
                  echo $version_str
                  exit 1
              fi
          fi
  Check-Specical-Words:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}","X-GitHub-Api-Version": "2022-11-28","Accept": "application/vnd.github+json"} }'
      - uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: debianCheck/do-with-data.py
          sparse-checkout-cone-mode: false
          path: debianCheck
      - run: |
          python3 debianCheck/debianCheck/do-with-data.py ${check_type} ${check_keys} fetch-api-data-action/data.json
        env:
          check_type: modify
          check_keys: getcap,setcap,lshw,dmidecode
      - name: Publish reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: specical-words-check-report
          path: result.json
  Check-Env-Set-Words:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}","X-GitHub-Api-Version": "2022-11-28","Accept": "application/vnd.github+json"} }'
      - uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: debianCheck/do-with-data.py
          sparse-checkout-cone-mode: false
          path: debianCheck
      - run: |
          python3 debianCheck/debianCheck/do-with-data.py ${check_type} ${check_keys} fetch-api-data-action/data.json
        env:
          check_type: all
          check_keys: export,unset
      - name: Publish reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: env-set-words-check-report
          path: result.json