name: Static Check
on: 
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
    secrets:
      access_token:
        required: true

jobs:
  Static-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Get Language
        if: always()
        id: get-language
        run: |
          wget -O getGithubChangeInfo.py https://raw.githubusercontent.com/linuxdeepin/.github/master/.github/tools/getGithubChangeInfo.py
          echo "lang=$(python3 getGithubChangeInfo.py ${{ inputs.repository }} ${{ secrets.access_token }})" >> $GITHUB_OUTPUT
      - name: Static Check with Go
        if: steps.get-language.outputs.lang == 'Go'
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Mod Check;
        if: steps.get-language.outputs.lang == 'Go' && hashFiles('go.mod') == ''
        run: |
          go mod init ${project}
          go mod tidy
      - name: Config check;
        if: steps.get-language.outputs.lang == 'Go' && hashFiles('.golangci.yml') == ''
        run: wget -O .golangci.yml https://raw.githubusercontent.com/linuxdeepin/.github/master/.github/tools/golangci.yml
        env:
          project: ${{ github.repository }}
      - name: GolangCILint Check
        if: steps.get-language.outputs.lang == 'Go'
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
      - name: Static Check with C
        if: steps.get-language.outputs.lang == 'C++'
        uses: linuxdeepin/action-cppcheck@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull_request_id: ${{ github.event.pull_request.number }}
          allow_approve: false