name: staticCheck
on: workflow_call


jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - id: static-check
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@static-check
      - if: always()
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@send-data
        with:
          testtype: "staticCheck"
          status: ${{ steps.static-check.outputs.summary-status }}
          result: ${{ steps.static-check.outputs.summary-result }}
      - if: always()
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@dbusapi-check