name: Static Check
on: workflow_call

jobs:
  Static-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Get Primary Language
        if: always()
        id: get-primary-language
        uses: fiddlermikey/action-get-primary-language@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
      - name: Static Check with Go
        if: steps.get-primary-language.outputs.primary_language == 'Go'
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Mod Check
        if: steps.get-primary-language.outputs.primary_language == 'Go' && hashFiles('go.mod') == ''
        run: |
          go mod init ${{ github.repository }}
          go mod tidy
      - name: Config check
        if: steps.get-primary-language.outputs.primary_language == 'Go' && hashFiles('.golangci.yml') == ''
        uses: actions/checkout@v4
        with:
          repository: kuchune/check-tools
          sparse-checkout: staticCheck/golangci.yml
          sparse-checkout-cone-mode: false
      - if: steps.get-primary-language.outputs.primary_language == 'Go' && hashFiles('.golangci.yml') == ''
        run: mv staticCheck/golangci.yml .golangci.yml
      - name: GolangCILint Check
        if: steps.get-primary-language.outputs.primary_language == 'Go'
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
      - name: Static Check with C
        if: steps.get-primary-language.outputs.primary_language == 'C++'
        uses: linuxdeepin/action-cppcheck@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull_request_id: ${{ github.event.pull_request.number }}
          allow_approve: false
      - name: Get Shell Files
        id: changed-shell-files
        uses: SkyHighGrowth/gha-changed-files@v1.0.1
        with:
          files: |
            **.sh
            **.bash
      - name: Static Check with sh
        if: steps.changed-shell-files.outputs.all_changed_files
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: ${{ steps.changed-shell-files.outputs.all_changed_files }}
          severity: error
          format: tty